defaults: &defaults
  qiniu_access_key: "xQrRKM14jlO50afZPn1oFMt6iPWmdaS7j-1HTzL1"
  qiniu_secret_key: "DJT5hp66aICddZjmnLLAIx1jwofJuKmJQryGcExQ"
  qiniu_bucket: "xingying"
  qiniu_bucket_domain: "xingying.qiniudn.com"
  title: "微媒"
  url_title: "微媒后台网站"
  page_desc: "一家微媒体平台，提供微信营销等服务"
  page_keywords: "微信, 微媒, 营销"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults