default: &default
  title: "微媒"
  url_title: "微媒后台网站"
  page_desc: "一家微媒体平台，提供微信营销等服务"
  page_keywords: "微信, 微媒, 营销"

development:
  <<: *default
  admin_emails:
    - 903279182@qq.com

test:
  <<: *default
  admin_emails:
    - 903279182@qq.com

production:
  <<: *default

  admin_emails:
    - 903279182@qq.com

