development:
  adapter: postgresql
  host: localhost
  database: yingxing_dev
  username: postgres
  password: '123456'
  encoding: UTF8
production:
  adapter: postgresql
  host: localhost
  database: yingxing_dev
  username: postgres
  password: '123456'
  encoding: UTF8
test:
  adapter: postgresql
  host: localhost
  database: yingxing_test
  username: postgres
  password: '123456'
  encoding: UTF8